GET http://localhost:5555/emp
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjV0YW4iLCJwYXNzd29yZCI6IjEyMzQ1IiwiaWF0IjoxNzAzOTg4NjQ2LCJleHAiOjE3MDM5ODg2NzZ9.IWR1mEKYKxKhdnIAgJaokT2-aN1P29W9SR9xyZSQNgg

###
POST http://localhost:5500/login
Content-Type: application/json

{
    "username": "5tan",
    "password": "12345"
}

###
POST http://localhost:5555/login
Content-Type: application/json

{
    "username": "5tan",
    "password": "12345"
}

###
POST http://localhost:5500/refreshToken
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjV0YW4iLCJwYXNzd29yZCI6IjEyMzQ1IiwiaWF0IjoxNzAzOTM1MjMyfQ.Wgb8Dtljam-9YZ6ZkoIQlwWDeJKOYBJl8CQBtQzwWIE"
}

###
POST http://localhost:5500/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjV0YW4iLCJwYXNzd29yZCI6IjEyMzQ1IiwiaWF0IjoxNzAzOTM1MjMyfQ.Wgb8Dtljam-9YZ6ZkoIQlwWDeJKOYBJl8CQBtQzwWIE"
}