GET http://localhost:5555/emp
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjV0YW4iLCJpYXQiOjE3MDM5MzUyOTQsImV4cCI6MTcwMzkzNTMyNH0.LOIXF82OKRU_K35XH0eECMS-n2snXwE-FJaNVwKf3Jc

###
POST http://localhost:5500/login
Content-Type: application/json

{
    "username": "5tan",
    "password": "12345"
}

###
POST http://localhost:5500/refreshToken
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjV0YW4iLCJwYXNzd29yZCI6IjEyMzQ1IiwiaWF0IjoxNzAzOTM1MjMyfQ.Wgb8Dtljam-9YZ6ZkoIQlwWDeJKOYBJl8CQBtQzwWIE"
}

###
POST http://localhost:5500/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjV0YW4iLCJwYXNzd29yZCI6IjEyMzQ1IiwiaWF0IjoxNzAzOTM1MjMyfQ.Wgb8Dtljam-9YZ6ZkoIQlwWDeJKOYBJl8CQBtQzwWIE"
}